# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ShoppingViewerFor11st' do
  pod 'Alamofire', '~> 1.3'
  pod 'SwiftyJSON', '~> 2.2.1'
end

target 'ShoppingViewerFor11stTests' do
  pod 'Alamofire', '~> 1.3'
  pod 'SwiftyJSON', '~> 2.2.1'
end

